version: 2
orbs:
  kubernetes: circleci/kubernetes@0.11.0
jobs:
  build:
    environment:
      IMAGE_NAME: swathithangaraj/building-on-ci
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: sudo docker build -t $IMAGE_NAME:latest .
      - run:
           name: Publish Docker Image to Docker Hub
           command: |
             echo "123cbe!@#" | sudo docker login -u "swathithangaraj" --password-stdin
               sudo docker push $IMAGE_NAME:latest
      - run:
          name: deploy to k8s
          command: |
            sudo kubectl
        
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
